### ISSUE TITLE
Please add learning.oreilly.com

### ISSUE THREAD

**Issue by Sirius2016** [fishjar/kiss-webfixer#1]
Please add learning.oreilly.com

Book page type translation

**Comment by fishjar** [comment]
1. Note: The functions of this project have been merged into the following two projects, so they will no longer be updated and are for reference only.

  - KISS Translator: https://github.com/fishjar/kiss-translator
  - Community subscription rules: https://github.com/fishjar/kiss-rules

2. I do not have an account with learning.oreilly.com, so I cannot provide translation assistance for this site.
